// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_MODE__', {
  value: "stealth",
  configurable: true, writable: true, enumerable: false
});
