// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_PV__', {
  value: "15.0.0",
  configurable: true, writable: true, enumerable: false
});
