// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"AT","tz":"Europe/Vienna","loc":"de-AT","intlLocale":"de","langs":["de-AT"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Hedda - German (Germany)","lang":"de-AT","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
