// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"BG","tz":"Europe/Sofia","loc":"bg-BG","intlLocale":"bg","langs":["bg-BG"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Ivan - Bulgarian (Bulgaria)","lang":"bg-BG","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
