// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"BR","tz":"America/Sao_Paulo","loc":"pt-BR","intlLocale":"pt-BR","langs":["pt-BR"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Maria - Portuguese (Brazil)","lang":"pt-BR","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
