// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"CZ","tz":"Europe/Prague","loc":"cs-CZ","intlLocale":"cs","langs":["cs-CZ"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Jakub - Czech (Czechia)","lang":"cs-CZ","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
