// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"DK","tz":"Europe/Copenhagen","loc":"da-DK","langs":["da-DK","da","en","en-US"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Helle - Danish (Denmark)","lang":"da-DK","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
