// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"FI","tz":"Europe/Helsinki","loc":"fi-FI","langs":["fi-FI","fi","en","en-US"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Heidi - Finnish (Finland)","lang":"fi-FI","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
