// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"HK","tz":"Asia/Hong_Kong","loc":"zh-HK","intlLocale":"zh-TW","langs":["zh-HK"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Huihui - Chinese (China)","lang":"zh-HK","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
