// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"HU","tz":"Europe/Budapest","loc":"hu-HU","langs":["hu-HU","hu","en","en-US"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Szabolcs - Hungarian (Hungary)","lang":"hu-HU","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
