// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"IQ","tz":"Asia/Baghdad","loc":"ar-IQ","intlLocale":"ar","langs":["ar-IQ"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Naayf - Arabic (Saudi Arabia)","lang":"ar-IQ","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
