// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"LU","tz":"Europe/Luxembourg","loc":"fr-LU","langs":["fr-LU","fr","de","en"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Hortense - French (France)","lang":"fr-LU","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
