// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"LV","tz":"Europe/Riga","loc":"lv-LV","intlLocale":"lv","langs":["lv-LV"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Everita - Latvian (Latvia)","lang":"lv-LV","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
