// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"NL","tz":"Europe/Amsterdam","loc":"nl-NL","langs":["nl-NL","nl","en","en-US"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Frank - Dutch (Netherlands)","lang":"nl-NL","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
