// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"NO","tz":"Europe/Oslo","loc":"nb-NO","intlLocale":"nb","langs":["nb-NO"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Hulda - Norwegian Bokmål (Norway)","lang":"nb-NO","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
