// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"PE","tz":"America/Lima","loc":"es-PE","intlLocale":"es-MX","langs":["es-PE"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Helena - Spanish (Spain)","lang":"es-PE","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
