// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"PT","tz":"Europe/Lisbon","loc":"pt-PT","langs":["pt-PT","pt","en","en-US"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Maria - Portuguese (Brazil)","lang":"pt-PT","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
