// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"SE","tz":"Europe/Stockholm","loc":"sv-SE","intlLocale":"sv","langs":["sv-SE"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Bengt - Swedish (Sweden)","lang":"sv-SE","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
