// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"TH","tz":"Asia/Bangkok","loc":"th-TH","intlLocale":"th","langs":["th-TH"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Pattara - Thai (Thailand)","lang":"th-TH","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
