// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_CC__', {
  value: {"cc":"TR","tz":"Europe/Istanbul","loc":"tr-TR","intlLocale":"tr","langs":["tr-TR"],"voices":[{"name":"Microsoft David - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Mark - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Zira - English (United States)","lang":"en-US","localService":true,"default":false},{"name":"Microsoft Tolga - Turkish (Türkiye)","lang":"tr-TR","localService":true,"default":true}]},
  configurable: true, writable: true, enumerable: false
});
