// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_DEV__', {
  value: {"id":"host","host":true},
  configurable: true, writable: true, enumerable: false
});
