// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.
Object.defineProperty(self, '__AFP_BOOT_DEV__', {
  value: {"id":"laptop_low","screenW":1366,"screenH":768,"dpr":1,"cores":4,"memory":4,"platform":"Win32","bluetooth":true,"glVendor":"Google Inc. (Intel)","glRenderer":"ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)","glParams":{"3379":16384,"32883":2048,"34024":16384,"34045":2,"34047":16,"34076":16384,"34921":16,"34930":16,"35071":2048,"35076":-8,"35077":7,"35371":12,"35657":4096,"35660":16,"35661":32,"36183":8,"36347":4096,"36348":30,"36349":1024},"glMaxAniso":16,"gpuVendor":"intel","gpuArch":"gen-9","gpuDevice":"","gpuDesc":"","av1":false},
  configurable: true, writable: true, enumerable: false
});
