/**
 * Generates dyn/ — the cold-start boot files.
 *
 * WHY THESE FILES EXIST
 *
 * On a freshly opened tab sessionStorage is empty, so profile-injector.js has nothing
 * to read at document_start and invents a neutral stub (laptop_mid / 1920x1080 / 8c /
 * Iris Xe / America/New_York). The real profile only arrives from background.js after
 * tabs.onUpdated reports 'complete'. Measured on the real extension: a page that reads
 * navigator.hardwareConcurrency in its first inline script sees 8 cores on a cold tab
 * and 16 after F5 — the same visitor, two machines, one reload apart.
 *
 * MV3 gives a content script no way to read extension state synchronously:
 * chrome.storage.* is async, and pushing from the service worker (webNavigation
 * .onCommitted + executeScript with injectImmediately) was measured and still loses —
 * the renderer does not wait for the browser process. The one channel that does land
 * in time is a content script whose data is already in the file it loads, which is why
 * the selection is spelled out as file names:
 *
 *   dyn/dev/<profileId>.js   the machine      (4 files)
 *   dyn/cc/<CC>.js           country/tz/locale (one per COUNTRY_DATA key)
 *   dyn/mode/<mode>.js       normal | stealth (2 files)
 *   dyn/pv/<win10|win11>.js  the host's UA-CH platformVersion bucket (2 files)
 *   dyn/ns/<pos><hex>.js     one hex digit of the master seed, AT one position (128 files)
 *   dyn/seedlib.js           seed-lib.js, wrapped, for the MAIN world
 *   dyn/boot.js              the assembler, hand-written, always registered last
 *
 * background.js registers the files matching the current selection — one dev, one cc, one
 * mode, one pv, the EIGHT ns files that spell the master seed, seedlib, then boot.js (see
 * registerBootScript). Changing the profile re-registers different files.
 *
 * Every value here is derived from the same tables background.js builds the real
 * profile from — GPU_DATA, COUNTRY_DATA and popup's PROFILES — using the same
 * derivations as buildProfile(), so the cold-start skeleton and the profile that
 * replaces it 300ms later cannot disagree. test/parity-static.mjs re-runs this
 * generator in memory and fails if any file on disk differs, so a table edit that
 * skips the generator is caught rather than shipped.
 *
 *   node tools/gen-dyn.mjs           write the files
 *   node tools/gen-dyn.mjs --check   report drift, write nothing (exit 1 if stale)
 */
import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';
import { root, loadBackground, loadPopup } from '../test/harness.mjs';

/** Every generated file, as { relative path -> contents }. The single source both the
 *  writer below and the parity test read. */
export function generate() {
  const { COUNTRY_DATA, GPU_DATA, afpSpeechVoices, WIN10_PLATFORM_VERSION, WIN11_PLATFORM_VERSION } =
    loadBackground(['COUNTRY_DATA', 'GPU_DATA', 'afpSpeechVoices', 'WIN10_PLATFORM_VERSION', 'WIN11_PLATFORM_VERSION']);
  const { PROFILES } = loadPopup(['PROFILES']);

  const files = {};
  const banner = '// Generated by tools/gen-dyn.mjs — do not edit. See that file for why.\n';

  // A bare `window.x = …` is enumerable and CreepJS reads Object.keys(window).slice(-50)
  // as "client code" litter — the same trap mw-core.js already documents for __p0. These
  // markers live for the length of one document_start and are deleted by dyn/boot.js,
  // but they are defined non-enumerable so that even mid-flight they are invisible.
  const slot = (name, value) =>
    banner +
    `Object.defineProperty(self, '${name}', {\n` +
    `  value: ${JSON.stringify(value)},\n` +
    '  configurable: true, writable: true, enumerable: false\n' +
    '});\n';

  // buildProfile(): profile.dpr wins when set; otherwise 1. The width-derived fallback is
  // gone — it read a CSS width as a panel size and so gave the widest screen the biggest
  // multiplier, which is backwards. See [FIX the-dpr-fallback-read-a-css-width-as-a-panel]
  // in background.js afpResolveDpr, and keep this in step with it.
  const dprOf = (p) => (typeof p.dpr === 'number' && isFinite(p.dpr) && p.dpr > 0) ? p.dpr : 1;
  // buildProfile(): deviceMemory is bucketed; 24/32/64 GB machines all report 32.
  const memOf = (m) => (m <= 2 ? 2 : m <= 4 ? 4 : m <= 8 ? 8 : m <= 16 ? 16 : 32);

  for (const p of PROFILES) {
    // [FIX host-mode] "This machine" carries no values: the page answers every hardware
    // field from the browser, and the popup's measurement travels through storage for the
    // audit's "claimed" column. The one thing the cold start must know is the FLAG, so it
    // stops substituting before the page's first script — same channel as the machine id.
    if (p.host) {
      files[`dyn/dev/${p.id}.js`] = slot('__AFP_BOOT_DEV__', { id: p.id, host: true });
      continue;
    }
    const gpu = GPU_DATA[p.gpuKey];
    if (!gpu) throw new Error(`popup PROFILES.${p.id} names gpuKey '${p.gpuKey}', absent from background GPU_DATA`);
    files[`dyn/dev/${p.id}.js`] = slot('__AFP_BOOT_DEV__', {
      id: p.id,
      screenW: p.screenW,
      screenH: p.screenH,
      dpr: dprOf(p),
      cores: p.cores,
      memory: memOf(p.memory),
      platform: p.platform,
      // buildProfile(): laptop_* carry a Bluetooth adapter, desktop pc_* do not.
      bluetooth: String(p.id).indexOf('pc_') !== 0,
      glVendor: gpu.unmaskedVendor,
      glRenderer: gpu.unmaskedRenderer,
      // [FIX cold-start-gl-limits] The two strings above were the whole GPU story here,
      // and the cold start left webglParams empty — so getParameter fell through to the
      // REAL driver for every numeric limit while UNMASKED_RENDERER already claimed the
      // spoofed card. MAX_TEXTURE_SIZE, MAX_VIEWPORT_DIMS, the shader-uniform counts:
      // an Arc telling you it is an Iris Xe, until the profile landed ~300ms later and
      // the same page reloaded into a different set of limits. This is the one measured
      // ANGLE/D3D11 table (see the note on GPU_DATA in background.js) and it belongs to
      // the machine, so it travels with the machine.
      glParams: gpu.webglParams || {},
      glMaxAniso: 16,
      // Same argument for WebGPU: adapter info is aligned with the same GPU_DATA entry
      // as WebGL, and a cold tab that answers WebGL "Iris Xe" and WebGPU "arc" is a
      // self-contradiction a page can read in one frame.
      gpuVendor: (gpu.webgpu && gpu.webgpu.vendor) || 'intel',
      gpuArch: (gpu.webgpu && gpu.webgpu.architecture) || '',
      gpuDevice: (gpu.webgpu && gpu.webgpu.device) || '',
      gpuDesc: (gpu.webgpu && gpu.webgpu.description) || '',
      // [FIX decoder-answered-for-the-host-gpu] Whether the claimed card decodes AV1 in
      // hardware — the one decodingInfo() flag that differs across these four cards.
      av1: !(gpu.hwDecode && gpu.hwDecode.av1 === false)
    });
  }

  for (const [cc, d] of Object.entries(COUNTRY_DATA)) {
    files[`dyn/cc/${cc}.js`] = slot('__AFP_BOOT_CC__', {
      cc,
      tz: d.tz,
      loc: d.loc,
      // buildProfile() derives navigator.languages from the Accept-Language string, so
      // the header and the JS list cannot drift apart. Same expression here.
      langs: d.lang.split(',').map((s) => s.trim().split(';')[0].trim()),
      // CreepJS reads speechSynthesis.getVoices() early — it gives up after 300ms — and
      // compares the default local voice's language with the Intl locale. Without this
      // the cold start fell back to the hardcoded en-US trio in mw/mw-canvas-audio.js,
      // whose default is Zira/en-US, and a de-DE or et-EE locale then read as
      // voiceLangMismatch → LowerEntropy.TIME_ZONE → Timezone and Intl marked bold-fail.
      voices: afpSpeechVoices(d.loc)
    });
  }

  for (const mode of ['normal', 'stealth']) {
    files[`dyn/mode/${mode}.js`] = slot('__AFP_BOOT_MODE__', mode);
  }

  // UA-CH platformVersion follows the HOST's Windows family, bucketed to two values —
  // it is not part of the profile the user picks, so it gets its own dimension. Without
  // it the cold start fell back to the '10.0.0' literal in profile-injector.js while the
  // DNR rule already sent the real bucket: measured on a Windows 11 host,
  // navigator.userAgentData.getHighEntropyValues() answered 10.0.0 for the first ~300ms
  // and 15.0.0 afterwards, with sec-ch-ua-platform-version="15.0.0" on every request
  // throughout. A page that reads client hints early — aff.top/tools/fingerprint does —
  // saw the JS layer claim Windows 10 under a Windows 11 header.
  files['dyn/pv/win10.js'] = slot('__AFP_BOOT_PV__', WIN10_PLATFORM_VERSION);
  files['dyn/pv/win11.js'] = slot('__AFP_BOOT_PV__', WIN11_PLATFORM_VERSION);

  // ── the master noise seed, spelled as file names ──────────────────────────────
  //
  // [FIX seed-was-a-named-page-readable-key] The per-domain canvas seed used to reach the
  // MAIN world through sessionStorage['afp_noise_seed_fallback'] — a key whose NAME said
  // "afp" and whose VALUE was the seed itself, sitting on the page's own origin where a
  // clean Chrome stores nothing at all. Because the noise is positional and deterministic
  // (hash(seed, absX, absY), ±1 per channel — protect_c.source and mw-canvas-audio compute
  // the same thing), a page that read that number could rebuild the mask analytically and
  // subtract it. The flat-region restore defeats the EMPIRICAL version of that attack, the
  // one that diffs a known image; it does not defeat one that never has to measure.
  //
  // The seed is a single 32-bit number, so it can travel the way the machine already does:
  // as file names. One-line files, each appending its own hex digit to the marker;
  // background.js registers the eight that spell the master seed, in order. That makes the
  // seed available to a MAIN-world document_start content script — before the page's first
  // line, and EARLIER than the sessionStorage write ever was (that one rode on an async
  // chrome.storage.local callback, ~8ms in).
  //
  // Why the master and not the per-domain value: the master is one number for the whole
  // install, so a fixed set of files covers every seed there is; the domain seed is per
  // site and cannot be enumerated.
  // dyn/boot.js derives it in the page with deriveDomainSeed, the same function background.js
  // and storage-bridge.js use — which is also why dyn/seedlib.js below exists.
  //
  // These files do NOT identify the user by themselves: the registration is invisible to the
  // page (a content script's file list is not observable from the page's realm), and each
  // file is one hex digit shared by every install whose seed has that digit in that position.
  //
  // [FIX repeated-nibble-collapsed-the-seed] The name carries the POSITION as well as the
  // digit — 128 files, `<pos><hex>.js` — and that is not tidiness, it is the whole reason
  // this works. The first version was sixteen files, one per digit, appended in order. A
  // seed whose hex form repeats a digit then names the same PATH twice in one js array, and
  // Chrome runs it once: the marker came back seven characters instead of eight, boot.js
  // rejected it, and the page silently fell back to the provisional host hash.
  //
  // Measured, on two runs of the same probe: master 90e31a5c (eight distinct digits) gave a
  // stable canvas hash across early and late reads; master 178f44ad (a repeated '4') gave a
  // flip in all three tabs. Only about 12% of seeds have eight distinct hex digits, so the
  // first version was broken for roughly seven installs in eight — and broken INVISIBLY,
  // because the fallback is a valid-looking number.
  //
  // With the position in the name, the eight registered paths are distinct by construction
  // no matter what the seed is, and boot.js reassembles by position rather than by arrival
  // order. test/coldstart.mjs pins it with a deliberately repetitive seed.
  for (let pos = 0; pos < 8; pos++) {
    for (const n of '0123456789abcdef') {
      files[`dyn/ns/${pos}${n}.js`] = banner +
        "Object.defineProperty(self, '__AFP_BOOT_NS__', {\n" +
        `  value: (self.__AFP_BOOT_NS__ || '') + '${pos}${n}',\n` +
        '  configurable: true, writable: true, enumerable: false\n' +
        '});\n';
    }
  }

  // deriveDomainSeed for the MAIN world. The ISOLATED world gets seed-lib.js from the
  // manifest and the service worker importScripts it, but the MAIN world can do neither —
  // the same constraint that makes mw-core.js keep its own copy of AFP_DEFAULT_FEATURES.
  // The difference is that this copy is GENERATED from the one source, verbatim, so it
  // cannot drift: test/parity-static.mjs re-runs this generator and fails if the file on
  // disk differs by a byte. Wrapped in a function so the two names stay out of the page's
  // global scope, and handed to boot.js through one non-enumerable marker like every other
  // value here.
  // The one edit to the copy: seed-lib.js carries `eslint-disable no-unused-vars` because
  // at top level its three functions are read from OTHER files, which a per-file linter
  // cannot see. Inside this wrapper all three are used right here, so the directive would
  // itself be flagged (reportUnusedDisableDirectives is on). Dropping the line is the whole
  // difference between the two files, and it changes no behaviour.
  // The second edit: afpTtPolicyName ([FIX policy-name-was-a-signature]) is appended to
  // seed-lib.js for background.js; the MAIN world gets it as mw-workers' own copy, pinned
  // by test/parity-static.mjs, and boot.js has no use for it — inside this wrapper it would
  // be an unused function, which the linter rightly refuses.
  const seedLib = fs.readFileSync(path.join(root, 'seed-lib.js'), 'utf8')
    .replace(/^\/\* eslint-disable no-unused-vars \*\/\r?\n/m, '')
    .replace(/\r?\n\/\*\*\r?\n \* \[FIX policy-name-was-a-signature\][\s\S]*$/, '\n');
  files['dyn/seedlib.js'] = banner +
    '(function () {\n' +
    seedLib +
    "\nObject.defineProperty(self, '__AFP_BOOT_SL__', {\n" +
    '  value: { d: deriveDomainSeed, h: afpEffectiveHostname, s: afpDeviceState },\n' +
    '  configurable: true, writable: true, enumerable: false\n' +
    '});\n' +
    '})();\n';

  return files;
}

// Importing this file (test/parity-static.mjs does) must not write anything; only
// running it as a command does.
if (import.meta.url !== pathToFileURL(process.argv[1] || '').href) {
  // imported — generate() is the whole API
} else {
  main();
}

function main() {
const check = process.argv.includes('--check');
const files = generate();
let stale = 0;

for (const [rel, body] of Object.entries(files)) {
  const abs = path.join(root, rel);
  const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (current === body) continue;
  stale++;
  if (check) {
    console.error(`stale: ${rel}`);
  } else {
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, body);
    console.log(`wrote ${rel}`);
  }
}

// A file left behind by a country or profile that no longer exists would still be
// registrable, so removal counts as drift too.
for (const dir of ['dyn/dev', 'dyn/cc', 'dyn/mode', 'dyn/pv', 'dyn/ns']) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) continue;
  for (const name of fs.readdirSync(abs)) {
    const rel = `${dir}/${name}`;
    if (files[rel]) continue;
    stale++;
    if (check) console.error(`orphan: ${rel}`);
    else { fs.unlinkSync(path.join(root, rel)); console.log(`removed ${rel}`); }
  }
}

if (check) {
  if (stale) {
    console.error(`\n${stale} file(s) out of date — run: node tools/gen-dyn.mjs`);
    process.exit(1);
  }
  console.log(`OK dyn/ matches the tables (${Object.keys(files).length} files)`);
} else {
  console.log(stale ? `\n${stale} file(s) updated` : `dyn/ already up to date (${Object.keys(files).length} files)`);
}
}
